'''
集合是无序可变，元素不能重复，实际上，集合底层是字典实现，集合的所有元素都是字典中键对象，与因此是不能重复的且唯一的
'''
a={3,5,7}
print(a)
a.add(9)
print(a)
#使用set()，将列表，元组等可迭代对象转成集合。如果原来数据存在重复数据，则只保留一个
b={233,2,30,'gg'}
b.add(30)
print(b)
b.remove('gg')
print(b)
b.clear()
print(b)

'''
集合相关操作，像数学中概念一样，python对集合也提供了并集，交集，差集等运算
'''
a={1,3,'sxt'}
b={'he','it','sxt'}
print(a|b)#并集
print(a&b)#交集
print(a-b)#差集
print(a.union(b))#并集
print(a.intersection(b))#交集
print(a.difference(b))#差集
