import turtle
turtle.width(10)#设置画笔粗度
'''画第一个⚪'''
turtle.color('blue')#画笔颜色改为红色
turtle.circle(50)
turtle.penup()#抬笔
turtle.goto(120,0)
'''画第二个⚪'''
turtle.color('black')
turtle.pendown()#下笔
turtle.circle(50)
turtle.penup()#抬笔
turtle.goto(240,0)
'''画第三个⚪'''
turtle.color('red')
turtle.pendown()#下笔
turtle.circle(50)
turtle.penup()#抬笔
turtle.goto(60,-50)
'''画第四个⚪'''
turtle.color('yellow')
turtle.pendown()#下笔
turtle.circle(50)
turtle.penup()#抬笔
turtle.goto(180,-50)
'''画第五个⚪'''
turtle.color('green')
turtle.pendown()#下笔
turtle.circle(50)